### ISSUE TITLE
ktool open error on macos

### ISSUE THREAD

**Issue by U5KUN** [0cyn/ktool#53]
` 
Hard fault in GUI due to uncaught exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.11/bin/ktool", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/ktool_script.py", line 409, in main
    args.func(args)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/ktool_script.py", line 489, in _open
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/ktool_script.py", line 481, in _open
    screen.load_file(args.filename, MMAP_ENABLED)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/window.py", line 2230, in load_file
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/window.py", line 2214, in load_file
    for item in KToolMachOLoader.contents_for_file(fd, self.update_load_status, mmap):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/window.py", line 1605, in contents_for_file
    raise ex
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/window.py", line 1603, in contents_for_file
    items.append(cls.slice_item(macho_slice, callback))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/window.py", line 1610, in slice_item
    loaded_image = MachOImageLoader.load(macho_slice)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/loader.py", line 58, in load
    MachOImageLoader._parse_load_commands(image, load_symtab, load_imports, load_exports)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/loader.py", line 80, in _parse_load_commands
    image.vm.add_segment(segment)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/image.py", line 51, in add_segment
    self.map_pages(segment.file_address, segment.vm_address, segment.size)
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/ktool/image.py", line 86, in map_pages
    raise MachOAlignmentError(f'Tried to map {hex(virtual_addr)}+{hex(size)} to {hex(physical_addr)}')
ktool.exceptions.MachOAlignmentError: Tried to map 0xe0000+0xe000 to 0xe0000`

### My env 
macOS Sonoma 14.0
Apple M1

**Comment by 0cyn** [comment]
This looks like an issue specific to a file, are you able to share the one that caused it here?
